name: Code Quality
on:
  - push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      pull-requests: write
      contents: read
      deployments: write
      id-token: write
    environment:
      name: npm
      url: https://www.npmjs.com/package/expo-alternate-app-icons
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx auto shipit
